### PR TITLE
Fixes usage of `ROUND_UP` and `ROUND_DOWN`

### LINKED ISSUE #133: Issue when forcing multiply and division to round the value using: ROUND_UP and ROUND_DOWN
Hi!

After upgrading from a previous version our test automation started picking up rounding issues when multiplying and dividing values, only when using `\Money\Money::ROUND_UP` && `\Money\Money::ROUND_DOWN`, e.g.:

```
// Calculation without rounding: 5321.27659574468085

// Returns: 5321 as expected
Money::GBP(2501)->divide(0.47);

// Returning: 5321 when it should return 5322
Money::GBP(2501)->divide(0.47, \Money\Money::ROUND_UP);
```

After looking into the code of the package we are using the native php round function which does not have ROUND_UP or ROUND_DOWN, after investigating MoneyPHP dependency they have their own private round method which uses **ceil** and **floor**.

I'm creating a PR for the fix, for your review.

Issue caused by: https://github.com/cknow/laravel-money/pull/117

Thank you!

### PR DESCRIPTION
**Pull request by tiagocyberduck**
Use parent dependency multiply and divide so we can cover the rounding.

Convert non-int multipliers to strings since we can only send int or floats to the \Money\Money class

Resolves #133

### CODE REVIEW

**Comment by mattvb91** [comment]
@ricardogobbosouza any update on this?

**Review by ricardogobbosouza — APPROVED** [review]

**Comment by ricardogobbosouza** [comment]
Thanks @tiagocyberduck

**Comment by mattvb91** [comment]
@ricardogobbosouza any chance of getting a new tag? Thank you and @tiagocyberduck

**Comment by ricardogobbosouza** [comment]
@mattvb91 released [v7.2.0](https://github.com/cknow/laravel-money/releases/tag/v7.2.0)

**Pull request merged**
