### PR TITLE
Add a sumMoney method to collections

### PR DESCRIPTION
**Pull request by jamiehd**
This allows $collection->sumMoney('attribute') to be used to get a total of money attributes.

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
I do not think it's necessary to add the library!
Does anyone think this is necessary?
Not to mention that you need to add tests for this!

**Comment by jamiehd** [comment]
Fair enough. It's just a snippet I've found myself using a lot so I assumed others may find it useful too.

**Comment by ricardogobbosouza** [comment]
Hi @jamiehd 
Now you can use the static method `Money::sum(Money::USD(10), Money::USD(20), Money::USD(30))`

**Comment by booni3** [comment]
Is it possible to sum a collection/array with the static method? What if the amount of elements are variable?

The collection helper looks nice.

**Pull request closed without merging**
