### PR TITLE
Workaroudn fixing filter_var issue

### PR DESCRIPTION
**Pull request by g4b0**
Fix for issue #107

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
@g4b0 
Could you add tests?

**Comment by g4b0** [comment]
@ricardogobbosouza adding tests I found a possible inconsistency in actual code (and also with my workaround). The following test is passing:
```
static::assertEquals(Money::parse(1, 'USD'), Money::USD(1));
static::assertEquals(Money::parse(1.00, 'USD'), Money::USD(100));
static::assertEquals(Money::parse('1', 'USD'), Money::USD(100));
```

IMHO 1, 1.00 and '1' should have the same value during parsing, shouldn’t it?

**Comment by ricardogobbosouza** [comment]
Remembering that we use https://www.moneyphp.org/ under the hood

**Comment by GreenImp** [comment]
Any chance of getting this merged in? I'm hitting issues where `10.00` is getting incorrectly cast to `0.10`.

**Pull request closed without merging**
