### PR TITLE
Add support php ^8.0

### LINKED ISSUE #72: `__callStatic` method ambiguity
[Here](https://github.com/cknow/laravel-money/blob/master/src/Money.php#L20) an alias is defined for `__callStatic`. But this method  exists in both `Cknow\Money\MoneyFactory` and `Illuminate\Support\Traits\Macroable` So in PHP8 this throws error.

Full error message: `An alias was defined for method __callStatic(), which exists in both Cknow\  
  Money\MoneyFactory and Illuminate\Support\Traits\Macroable. Use Cknow\Money  
  \MoneyFactory::__callStatic or Illuminate\Support\Traits\Macroable::__callS  
  tatic to resolve the ambiguity`

### PR DESCRIPTION
**Pull request by rez1dent3**
Resolve #72

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
Hi @rez1dent3 
Needs to add in CI https://github.com/cknow/laravel-money/blob/master/.github/workflows/tests.yml#L18

**Comment by rez1dent3** [comment]
@ricardogobbosouza Added, fixed the problems. The bugs that appeared are related to the package being used for test coverage. It uses the Deprecated class. I can't do anything here)

**Comment by rez1dent3** [comment]
@ricardogobbosouza In theory, it can be removed.
```php
 Macroable::__callStatic as macroableCallStatic;
```

**Comment by ricardogobbosouza** [comment]
@rez1dent3 
in theory yes

**Pull request merged**
