### PR TITLE
Serializer Config

### PR DESCRIPTION
**Pull request by adrum**
This allows for multiple serialization formats. It keeps the default while allowing other serialization types, such as decimal, integer and intl.

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
Hi @adrum 
Could you give an example use case?

**Comment by adrum** [comment]
@hasfoug that's exactly the use case I had. We just needed the decimal amount and not the full money object parts. 

The project I used this on did not need currency included when serializing our Money values. We are already using this branch in our project months prior to the initial PR creation, so I figured I would formalize it for a PR to see if there was interest in upstreaming it. 

It in theory supports providing serializer class, in case the options available do not meets someone's needs.

**Comment by Artessan** [comment]
this is useful when the model is serialized and deserialized ex: direct binding as livewire property or queue job when the model has to be passed as array and then build using new Model(array).

As the serialization generate an array for the field when the  "new model" is used the cast throw an error. This could be solved with this pr or adding in each cast the check for array and validating the amount value with the type of the cast

**Comment by adrum** [comment]
@ricardogobbosouza We should be good to go with tests! Let me know if you think of anything else.

**Review by ricardogobbosouza — APPROVED** [review]

**Comment by ricardogobbosouza** [comment]
Thanks @adrum

**Pull request merged**
