### PR TITLE
Laravel 7 custom cast

### PR DESCRIPTION
**Pull request by cerbero90**
Following up @atymic's issue https://github.com/cknow/laravel-money/issues/48, this draft contains a possible candidate to cast values into Money by leveraging the new [Laravel 7 feature](https://laravel.com/docs/7.x/eloquent-mutators#custom-casts).

At this stage the cast can be defined in the following ways:
```php
protected $casts = [
    // cast money using the currency defined in the package config
    'money' => MoneyCast::class,
    // cast money using the defined currency
    'money' => MoneyCast::class . ':AUD',
    // cast money using the currency defined in the model attribute 'currency'
    'money' => MoneyCast::class . ':currency',
];
```
In the example above, if the model attribute `currency` is `null`, the currency defined in the package configuration is used instead.

Setting money can be done in several ways:
```php
$model->money = 10; // 10.00 USD or any other currency defined
$model->money = 10.23; // 10.23 USD or any other currency defined
$model->money = 'A$10'; // 10.00 AUD
$model->money = '1,000.23'; // 1000.23 USD or any other currency defined
$model->money = '10'; // 0.10 USD or any other currency defined
$model->money = new Cknow\Money\Money('10', new Money\Currency('EUR')); // 10 EUR
```
When we pass the model attribute holding the currency, such attribute is updated as well when setting money:
```php
$model->currency; // null
$model->money = '€13';
$model->currency; // 'EUR'
$model->money->getAmount(); // '1300'
```
Given that only the class introduced in this PR implements the new interface `CastsAttributes`, we may not need a major version bump as long as the new tests (to be added once we agree on the implementation) are excluded from builds that use versions of Illuminate packages prior to 7.

Please let me know if you have any feedback or thoughts about the version bumping.

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
@cerbero90 looks very good 😄

**Comment by cerbero90** [comment]
Thanks @ricardogobbosouza, if you reckon that no changes are needed I'll move on and add tests.

On a second thought, a major version bump with an update of composer dependencies might be a safer option. What do you think?

**Comment by ricardogobbosouza** [comment]
@cerbero90 without a doubt, in another PR I will launch the v5, drop support for Laravel 6

**Comment by cerbero90** [comment]
That is great, thanks @ricardogobbosouza.

Before creating the tests, I'd like your opinion on casting Money from a string. Currently we cast strings like the Money library does, i.e. `"10"` = `0.10`. This is not consistent with the way that other types are casted though, e.g. the integer `10` = `10.00`.

What approach do we prefer, being consistent with the way Money works or being consistent with how the other types are casted?

**Comment by ricardogobbosouza** [comment]
Like Money works, we work on it

**Comment by cerbero90** [comment]
Updated and added tests. While creating tests I bumped into this issue: https://github.com/cknow/laravel-money/issues/54

However the casting feature itself is not compromised by that issue.

**Comment by cerbero90** [comment]
@ricardogobbosouza not sure why but there are two dependencies that takes ages and fail to be installed:
```
povils/phpmnd
sebastian/phpcpd
```

While creating this PR, I had to skip the installation of those two dependencies and the builds seem to have the same issue: https://ci.appveyor.com/project/ricardogobbosouza/laravel-money/builds/32595998

**Comment by cerbero90** [comment]
@ricardogobbosouza any thoughts?

**Comment by ricardogobbosouza** [comment]
Hi @cerbero90 
Sorry for the delay, I still haven't been able to revise it.

**Comment by ricardogobbosouza** [comment]
Now it's failed on the appveyor :sweat_smile:

**Comment by cerbero90** [comment]
Thanks @ricardogobbosouza for your time. It looks like grumphp does not support composer 2. There is also an open issue for that: https://github.com/phpro/grumphp/issues/756

**Pull request merged**
