### PR TITLE
upgrade to moneyphp/money 4

### PR DESCRIPTION
**Pull request by joostdebruijn**
This PR upgrades to money version 4. It should be a major release:

- Money 4 requires PHP 8.0 as minimal version, so this package requires PHP 8.0 as minimum also
- The signature for helpers changed -> Money 4 doesn't accept strings anymore for `$fallbackCurrency`. I now changed it that a Money\Currency is required (as required by `parse`), however - it is also possible to edit the helper functions in such way the string will be parsed correctly.

There is one failing test, wich may need a fix upstream. The test `testSetCurrenciesWrongCustomCurrenciesConfig` failes because no `InvalidArgumentException` is thrown for the custom currencies while they have not an integer for the subunit. At this moment I could not figure out where this goes wrong.

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
Thanks @joostdebruijn 

- I intend to continue accepting strings in currencies

As this package uses `moneyphp/money` the idea is to make it easier to use =)

**Comment by joostdebruijn** [comment]
Hi @ricardogobbosouza. Fixed that!

The test `testSetCurrenciesWrongCustomCurrenciesConfig` still fails...

**Comment by billriess** [comment]
Any progress on this? If there are breaking changes, maybe bump the major version for this release?

**Comment by ricardogobbosouza** [comment]
Continue #91

**Pull request closed without merging**
