### PR TITLE
Support moneyphp/money 4

### LINKED ISSUE #85: Support `moneyphp/money` 4.0
A new version of the money library was released, it'd be great if this package could be updated to support it.

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
Resolve #85

### CODE REVIEW

**Comment by joostdebruijn** [comment]
Hi @ricardogobbosouza, do you have plans to bring out a new release out soon? Would like to have this merged PR in a new release. :)

**Comment by ricardogobbosouza** [comment]
Hi @joostdebruijn 
I must release this week =)

**Comment by ricardogobbosouza** [comment]
Hi @joostdebruijn 
Released https://github.com/cknow/laravel-money/releases/tag/v6.2.0

**Comment by joostdebruijn** [comment]
@ricardogobbosouza Very nice, thanks for the headsup!

**Pull request merged**
